---

- name: Create openshift-api-secret
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: false
    state: present
    definition: "{{ lookup('template', '{{ playbook_dir }}/roles/certs/templates/api-secret.yaml.j2') }}"

- name: Update API Server with Cert
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: false
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir=api_cert_dir) }}"
  register: api_cert_kustomize
