---
- name: Create Infra MachineConfigPools
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '{{ playbook_dir }}/roles/machineconfigpool/templates/mcp.yaml.j2') }}"
  loop:
    - infra
    - storage

- name: Create Infra MachineConfigs
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '{{ playbook_dir }}/roles/machineconfigpool/templates/mc.yaml.j2') }}"
  loop:
    - infra
    - storage
