- op: add
  path: /spec/identityProviders/-
  value:
    name: ldap
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        email: []
        id:
        - sAMAccountName
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      bindDN: >-
        CN=bindDNInfo,OU=DomainOU,DC=domain,DC=org
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: "ldaps://domain.org/DC=DOM,DC=ORG?sAMAccountName?sub?(|(member_info))"
