kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../base

patchesJson6902:
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: ldap-group-syncer
    path: cron-patch.yaml
