kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secrets-management
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["get", "patch", "delete", "create"]
