---
- name: Run command locally
  delegate_to: localhost
  block:
    - name: Get nodes
      kubernetes.core.k8s_info:
        kind: "Node"
        validate_certs: false
        label_selectors:
          - "node-role.kubernetes.io/infra"
          - "node-role.kubernetes.io/storage!="
      register: infra_nodes

    - name: Set infra node names
      ansible.builtin.set_fact:
        node_names: "{{ infra_nodes.resources | map(attribute='metadata.name') | list }}"

    - name: Check node names
      ansible.builtin.debug:
        var: node_names

- name: Apply taints to nodes
  ansible.builtin.include_tasks: taints.yaml

- name: Apply tolerations
  ansible.builtin.include_tasks: tolerations.yaml
