---
- name: Taint infra nodes
  kubernetes.core.k8s_taint:
    state: present
    name: "{{ item }}"
    taints:
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: "reserved"
      - key: node-role.kubernetes.io/infra
        value: reserved
        effect: NoSchedule
  loop: "{{ node_names }}"
