---
- name: Apply tolerations and increase replicas for IngressController
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: IngressController
      metadata:
        name: default
        namespace: openshift-ingress-operator
      spec:
        replicas: 3
        nodePlacement:
          nodeSelector:
            matchLabels:
              node-role.kubernetes.io/infra: ""
          tolerations:
            - effect: NoSchedule
              key: infra
              operator: Equal
              value: reserved
            - effect: NoExecute
              key: infra
              operator: Equal
              value: reserved
