kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../base

patchesJson6902:
  - target:
      group: config.openshift.io
      version: v1
      kind: OperatorHub
      name: cluster
    path: operator-disable.yaml
