---
- name: Get hosts for base plays
  hosts: localhost
  gather_facts: false

- name: Perform base config
  ansible.builtin.import_playbook:
    base_playbook.yaml

- name: Configs for playbook
  hosts: localhost
  gather_facts: false

  environment:
    # K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  vars:
    api_cert_dir: "{{ catalog_dir }}/cert-patches/openshift-api-certificate/overlays/{{ cluster }}"

  tasks:

    - name: Create and apply security certificates for cluster
      ansible.builtin.import_role:
        name: certs
