---
- name: Get hosts for base playbook
  hosts: localhost
  gather_facts: true

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for playbook
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Set chrony configuration on VMs
      import_role:
        name: chrony
