---
- name: Get hosts for base playbook
  hosts: localhost
  gather_facts: true

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for playbook
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Remove default kubeadmin secret
      kubernetes.core.k8s:
        kubeconfig: "{{ KUBECONFIG }}"
        state: absent
        kind: Secret
        name: kubeadmin
        ns: kube-system
        api_version: v1
