---
- name: Get hosts for base playbook
  hosts: localhost
  gather_facts: true

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for playbook
  hosts: localhost
  gather_facts: true

  vars_prompt:

    - name: role_assigned
      prompt: "What role should be assigned to machinesets?"
      default: "infra"
      private: false

  vars:

    api_cert_dir: "{{ catalog_dir }}/cert-patches/openshift-api-certificate/overlays/{{ cluster }}"
    ldap_dir: "{{ catalog_dir }}/oauth/overlays/ldap"
    groupsync_dir: "{{ catalog_dir }}/ldapcron/overlays"
    role_binding_dir: "{{ catalog_dir }}/groups-role-bindings/base"

  tasks:

    - name: Cluster being built
      ansible.builtin.debug:
        msg: "Finalizing the {{ cluster }} cluster."

    - name: Results of Machineset Prompt
      ansible.builtin.debug:
        msg: "You are creating {{ role_assigned }} machinesets"

    # Apply Certs
    - name: Apply Certs
      ansible.builtin.import_role:
        name: certs

    - name: Create Machine Config Pools
      ansible.builtin.import_role:
        name: machineconfigpool

    - name: Create Machinesets
      ansible.builtin.import_role:
        name: machinesets

    - name: Apply LDAP Oauth to Cluster
      ansible.builtin.import_role:
        name: ldap

    - name: Create LDAP Sync Jobs
      ansible.builtin.import_role:
        name: LDAPgroupSync

    - name: Apply Taints and Tolerations to infra Nodes
      ansible.builtin.import_role:
        name: node_config
