---
- name: Get hosts for base playbook
  hosts: localhost
  gather_facts: true

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Configs for playbook
  hosts: localhost
  gather_facts: false

  environment:
    K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  tasks:

  - name: Install Image Registry
    ansible.builtin.import_role:
      name: image_registry
