---
- name: Get host info for base plays
  hosts: localhost

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get host info for playbook
  hosts: localhost
  gather_facts: false

  vars:
    ldap_dir: "{{ catalog_dir }}/oauth/overlays/ldap"

  environment:
    K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  tasks:

    - name: Set LDAP ConfigMap and ldap-secret
      ansible.builtin.import_role:
        name: ldap
