---
- name: Get hosts for base config
  hosts: localhost

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for playbook work
  hosts: localhost
  gather_facts: false
  become: false

  environment:
    K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  vars:
    build:
      "{% if cluster=='quay' or cluster=='mquay' %}quay{% else %}ocp{% endif %}"
    groupsync_dir: "{{ catalog_dir }}/ldapcron/overlays/{{ build }}"
    role_binding_dir: "{{ catalog_dir }}/groups-role-bindings/base"

  tasks:

    - name: Create LDAP Group Sync ConfigMaps and ServiceAccount
      ansible.builtin.import_role:
        name: LDAPgroupSync
