---
- name: Get hosts for base
  hosts: localhost
  gather_facts: true

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for playbook
  hosts: localhost
  gather_facts: false
  become: false

  # Left GOVC Code for reference; although currently unused
  environment:
    K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"
    # GOVC_USERNAME: "{{ vcenter.service_account_username }}"
    # GOVC_PASSWORD: "{{ vcenter.service_account_password }}"
    # GOVC_URL: "https://{{ vcenter.ip }}"
    # GOVC_DATACENTER: "{{ vcenter.datacenter }}"
    # GOVC_INSECURE: 1

  tasks:
    - name: Results of Prompt
      ansible.builtin.debug:
        msg: "You are creating {{ role_assigned }} machinesets"

    - name: Create Machinesets
      ansible.builtin.import_role:
        name: machinesets
