---
- name: Hosts for base playbook
  hosts: localhost
  gather_facts: true

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for MCP Play
  hosts: localhost
  gather_facts: true

  environment:
    K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  tasks:

    - name: Create Machine Config Pools
      ansible.builtin.import_role:
        name: machineconfigpool
