---
- name: Get hosts for base plays
  hosts: localhost

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for playbook
  hosts: localhost
  gather_facts: true
  become: false

  environment:
    K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  tasks:

  - name: Update Monitoring Node Selectors
    ansible.builtin.import_role:
      name: monitoring_configs
