---
- name: Get hosts for base plays
  hosts: localhost

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for playbook
  hosts: localhost
  gather_facts: true
  become: false

  environment:
    K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  vars:
    ns: openshift-config

  tasks:

    - name: Create Namespace if necessary
      ansible.builtin.import_role:
        name: create_namespace

    - name: Deploy Network Policy
      ansible.builtin.import_role:
        name: network_policy
