---
- name: Get hosts for base plays
  hosts: localhost

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for current plays
  hosts: localhost
  gather_facts: false
  become: false

  environment:
    K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  # vars:
  #   install_mode: "{{ install_mode }}"
  #   namespace: "{{ namespace }}"
  #   operator: "{{ operator }}"
  #   channel: "{{ channel }}"

  tasks:

    - name: Create namespace if needed
      ansible.builtin.import_role:
        name: create_namespace

    - name: Install Operators
      ansible.builtin.import_role:
        name: operators_install
