---
- name: Get hosts for base plays
  hosts: localhost

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for current plays
  hosts: localhost
  gather_facts: false
  become: false

  environment:
    K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  tasks:

    - name: Update Cluster Pull-Secret
      ansible.builtin.import_role:
        name: update_pullsecret
