---
- name: Get hosts for base plays
  hosts: localhost

- name: Perform base config
  import_playbook:
    base_playbook.yaml

- name: Get hosts for current plays
  hosts: localhost
  gather_facts: false
  become: false

  environment:
    K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  vars:
    update_service_patch_dir: "{{ catalog_dir }}/update-service/overlays"
    ns: openshift-update-service
    operator: cincinnati-operator
    install_mode: OwnNamespace
    channel: v1

  tasks:

    - name: Patch Update Service Operator
      ansible.builtin.import_role:
        name: update_service
